spring.application.name=uberweb
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cabconnectdb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Spal#@123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#add this line to run data.sql on spsqltartup
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#security config
jwt.secretKey=paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823


