spring.application.name=uberweb

spring.profiles.active=dev

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cabconnectdb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Spal#@123
spring.jpa.hibernate.ddl-auto=create

#smtp config
spring.mail.username=sachin004pal@gmail.com
spring.mail.password=rtjt witn wxbo iych
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secretKey = paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823





